name: ❌ Bug Report [English]
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Before submitting this issue, please ensure that you have read the [github issues](https://github.com/3hx/cursor-free-vip/issues)

  - type: checkboxes
    id: checklist
    attributes:
      label: Preflight Checklist
      description: |
        Please ensure that all of the following are checked before submitting your issue
      options:
        - label: I understand that issues are for problem-solving, not a comment section, and I will provide as much information as possible to help resolve the issue.
          required: true
        - label: I have checked the top Issue and searched for existing [open issues](https://github.com/3hx/cursor-free-vip/issues) and [closed issues](https://github.com/3hx/cursor-free-vip/issues?q=is%3Aissue%20state%3Aclosed%20), and found no similar issues.
          required: true
        - label: I have filled in a brief, clear, and specific title to help the developer quickly determine the general issue when reviewing the Issue list, rather than "a suggestion", "stuck", etc.
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Windows x32
        - Windows x64
        - macOS Intel
        - macOS ARM64
        - Linux x64
        - Linux ARM64
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Cursor Free Vip are you running?
      placeholder: For example v1.0.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the problem as detailed as possible
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Related log output
      description: Please copy and paste any related log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Anything that might help us understand the problem better
